name: Update Data

on: push

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Execute Script
        run: pnpm start

      - name: Run Test
        run: pnpm test

      - name: Update Docs
        run: pnpm md-magic

      - name: Add File
        run: |
          git config --local user.email "${{ secrets.USER_EMAIL }}"
          git config --local user.name "zakiego"
          git add .

      - name: Check is need to push
        id: check_status
        run: |
          STATUS=$(git status --porcelain | wc -l)
          echo "number of files that need to be committed:" $STATUS
          echo "::set-output name=STATUS::$STATUS"

      - name: Commit File
        if: steps.check_status.outputs.STATUS > 0
        run: |
          echo "status"
          now=$(date)
          git commit -m "feat: update data $now"

      - name: Push Changes
        if: steps.check_status.outputs.STATUS > 0
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Setup Python
        if: steps.check_status.outputs.STATUS > 0
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Python Lib
        if: steps.check_status.outputs.STATUS > 0
        run: pip install -r src/requirements.txt

      - name: Push to Google Sheets
        if: steps.check_status.outputs.STATUS > 0
        run: python src/push.py ${{ secrets.GOOGLE_CREDENTIALS }}
